licenses(["notice"])  # BSD

package(default_visibility = ["//visibility:public"])

exports_files(
    [
        "libsvm_nu_svr_model.txt",
        "tcdvoip_nu.568_c5.31474325639_g3.17773760038_model.txt",
        "lattice_tcditugenmeetpackhref_ls2_nl60_lr12_bs2048_learn.005_ep2400_train1_7_raw.tflite",
        "lattice_nsimstddeg_tfcompile_config.pbtxt",
    ],
)

filegroup(
    name = "tflite_speech_lattice_default_model",
    srcs = ["lattice_tcditugenmeetpackhref_ls2_nl60_lr12_bs2048_learn.005_ep2400_train1_7_raw.tflite"],
)
