licenses(["notice"])  # BSD

package(default_visibility = ["//visibility:public"])

exports_files([
    "castanets48_stereo.wav",
    "contrabassoon48_stereo.wav",
    "contrabassoon48_stereo_24kbps_aac.wav",
    "glock48_stereo.wav",
    "glock48_stereo_48kbps_aac.wav",
    "guitar48_stereo.wav",
    "guitar48_stereo_64kbps_aac.wav",
    "harpsichord48_stereo.wav",
    "harpsichord48_stereo_96kbps_mp3.wav",
    "moonlight48_stereo.wav",
    "moonlight48_stereo_128kbps_aac.wav",
    "ravel48_stereo.wav",
    "ravel48_stereo_128kbps_opus.wav",
    "sopr48_stereo.wav",
    "sopr48_stereo_256kbps_aac.wav",
    "steely48_stereo.wav",
    "steely48_stereo_lp7.wav",
    "strauss48_stereo.wav",
    "strauss48_stereo_lp35.wav",
])
