licenses(["notice"])  # BSD

py_binary(
    name = "fit_nsim_to_mos_poly",
    srcs = ["fit_nsim_to_mos_poly.py"],
    deps = ["@numpy"],
)

py_binary(
    name = "make_svm_train_file",
    srcs = ["make_svm_train_file.py"],
)
