licenses(["notice"])  # BSD

package(default_visibility = ["//visibility:public"])

exports_files([
    "alignment/reference.wav",
    "alignment/degraded.wav",
    "clean_speech/CA01_01.wav",
    "clean_speech/transcoded_CA01_01.wav",
    "mismatched_duration/guitar48_stereo_x2.wav",
    "mismatched_duration/guitar48_stereo_middle_2sec_cut.wav",
    "mismatched_duration/guitar48_stereo_middle_50ms_cut.wav",
    "filtered_freqs/guitar48_stereo_10k_filtered_freqs.wav",
    "long_duration/1_min/guitar48_stereo_deg_1min.wav",
    "long_duration/1_min/guitar48_stereo_deg_25s.wav",
    "long_duration/1_min/guitar48_stereo_ref_1min.wav",
    "long_duration/1_min/guitar48_stereo_ref_25s.wav",
    "non_48k_sample_rate/guitar48_stereo_44100Hz.wav",
    "short_duration/1_sample/guitar48_stereo_1_sample.wav",
    "short_duration/10_sample/guitar48_stereo_10_sample.wav",
    "short_duration/100_sample/guitar48_stereo_100_sample.wav",
    "short_duration/1000_sample/guitar48_stereo_1000_sample.wav",
    "short_duration/10000_sample/guitar48_stereo_10000_sample.wav",
    "short_duration/1_second/guitar48_stereo_1_sec.wav",
    "short_duration/5_second/guitar48_stereo_5_sec.wav",
    "svr_training/training_mat_tcdaudio14_aacvopus15_moslqs.txt",
    "svr_training/training_mat_tcdaudio14_aacvopus15_fvnsims.txt",
    "test_model/cpp_model.txt",
    "example_batch/batch_input.csv",
])
